# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b701a12f7285ec742df02722508c6d3a2001cf5ea71a1eec34ddcb6db6ca699976df379efe08901e75a1ea6e37f555b7f5f2e00c6160a34ada59bf906aa452a1

test:
  secret_key_base: bf4a2cf16ae235472bc5f013b55d94df1dded98859555930ce116eb4fb1502f576b44a2bf367ecb1d25c471027c362e8aba7b3fa896f5aaceca8b08898ef24ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
